import Head from "next/head";
import { PropsWithChildren } from "react";

import Footer from "./Footer";
import styles from "../../../styles/Home.module.css";

const index = ({ children }: PropsWithChildren<unknown>) => {
  return (
    <>
      <Head>
        <title>NUMBLE:: 쿠팡 클론</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <main className={styles.main}>{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default index;
